name: Deploy with Manual Approval

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build App
        run: echo "Building the app..."

  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Deploy test-App
        run: echo "Deploying to testing environment..."



  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Deploy App
        run: echo "Deploying to production..."
