# .github/workflows/build.yml

name: Reusable Build

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print language
        run: echo "Building a ${{ inputs.language }} project"
