# .github/workflows/reusable-add.yml

name: Add Two Numbers

on:
  workflow_call:
    inputs:
      number1:
        description: 'First number'
        required: true
        type: number
      number2:
        description: 'Second number'
        required: true
        type: number

jobs:
  add-numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Add the numbers
        run: |
          echo "First number: ${{ inputs.number1 }}"
          echo "Second number: ${{ inputs.number2 }}"
          sum=$(( ${{ inputs.number1 }} + ${{ inputs.number2 }} ))
          echo "Sum: $sum"
