name: Custom-variables

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Access Secret
        env:
          SECRET: ${{ secrets.DB_PASSWORD }}
          VARIABLE: ${{secrets.ENVIRONMENT}}
        run: |
          echo "Secret value:$SECRET"
          echo "non sensitive variable env is:$VARIABLE"
