name: Custom-variables

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Access Secret
        env:
          SECRET: ${{ secrets.DB_PASSWORD }}
        run: echo "Secret value: $SECRET"
